using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using Microsoft.Extensions.Logging;

namespace AutoGithubChangelogPoster.Services;

public partial class TweetFormatterService
{
    private readonly ILogger<TweetFormatterService> _logger;
    private readonly ReleaseSummarizerService? _releaseSummarizer;

    private const int MaxTweetLength = 280;
    private const int MaxPremiumTweetLength = 25000;
    private const int UrlLength = 23;

    private static readonly Regex ListItemPattern = new(@"<li[^>]*>(.*?)</li>", RegexOptions.IgnoreCase | RegexOptions.Singleline | RegexOptions.Compiled);
    private static readonly Regex CodeTagPattern = new(@"</?code[^>]*>", RegexOptions.IgnoreCase | RegexOptions.Compiled);
    private static readonly Regex MarkdownLinkPattern = new(@"\[([^\]]+)\]\([^\)]+\)", RegexOptions.Compiled);
    private static readonly Regex HtmlTagPattern = new(@"<[^>]+>", RegexOptions.Compiled);
    private static readonly Regex WhitespacePattern = new(@"\s+", RegexOptions.Compiled);
    private static readonly Regex BulletPrefixPattern = new(@"^\s*[-*•]+\s*", RegexOptions.Compiled);
    private static readonly Regex LeadingPunctuationPattern = new(@"^[\p{P}\s]+", RegexOptions.Compiled);

    public TweetFormatterService(ILogger<TweetFormatterService> logger, ReleaseSummarizerService? releaseSummarizer = null)
    {
        _logger = logger;
        _releaseSummarizer = releaseSummarizer;
    }

    private static int GetTextLength(string text, bool useXWeightedLength)
        => useXWeightedLength ? XPostLengthHelper.GetWeightedLength(text) : text.Length;

    private bool ShouldUseAiFromEnvironment()
    {
        var enableAi = Environment.GetEnvironmentVariable("ENABLE_AI_SUMMARIES");
        return !string.IsNullOrEmpty(enableAi) && bool.Parse(enableAi);
    }

    private static List<string> ExtractFeatureList(string htmlContent, int maxItems = int.MaxValue)
    {
        var features = new List<string>();

        var matches = ListItemPattern.Matches(htmlContent);
        foreach (Match match in matches)
        {
            var feature = CleanFeatureText(match.Groups[1].Value);
            if (!string.IsNullOrWhiteSpace(feature))
            {
                features.Add(feature);
            }
        }

        if (features.Count == 0)
        {
            var lines = htmlContent.Split(['\n', '\r'], StringSplitOptions.RemoveEmptyEntries);
            foreach (var line in lines)
            {
                if (line.TrimStart().StartsWith("- ", StringComparison.Ordinal) ||
                    line.TrimStart().StartsWith("* ", StringComparison.Ordinal))
                {
                    var feature = CleanFeatureText(line);
                    if (!string.IsNullOrWhiteSpace(feature))
                    {
                        features.Add(feature);
                    }
                }
            }
        }

        return features
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Take(maxItems)
            .ToList();
    }

    private static string CleanFeatureText(string text)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return string.Empty;
        }

        var cleaned = HttpUtility.HtmlDecode(text);
        cleaned = MarkdownLinkPattern.Replace(cleaned, "$1");
        cleaned = CodeTagPattern.Replace(cleaned, string.Empty);
        cleaned = HtmlTagPattern.Replace(cleaned, " ");
        cleaned = WhitespacePattern.Replace(cleaned, " ").Trim();
        cleaned = BulletPrefixPattern.Replace(cleaned, string.Empty);
        cleaned = LeadingPunctuationPattern.Replace(cleaned, string.Empty).Trim();

        if (string.IsNullOrWhiteSpace(cleaned) ||
            cleaned.Contains("made their first contribution", StringComparison.OrdinalIgnoreCase) ||
            cleaned.StartsWith("Full Changelog", StringComparison.OrdinalIgnoreCase) ||
            cleaned.StartsWith("Generated by", StringComparison.OrdinalIgnoreCase))
        {
            return string.Empty;
        }

        return cleaned.Length > 120 ? cleaned[..117] + "..." : cleaned;
    }

    private const int ThreadBuffer = 20;
    private const int MaxThreadPosts = 4;
    private const int ThreadIndicatorReserve = 8;
    private const int SinglePostMaxLength = 260;
    private const int SinglePostBuffer = 4;
    private const int ThreadParagraphMaxLength = 200;
    private const int PremiumParagraphMaxLength = 420;
    private const string GitHubHashtag = "#GitHub";
    private const string CopilotHashtag = "#GitHubCopilot";
    private const string ActionsHashtag = "#GitHubActions";
    private const string CodespacesHashtag = "#GitHubCodespaces";
    private const string CliHashtag = "#GitHubCLI";
    private const string EnterpriseHashtag = "#GitHubEnterprise";
    private const string IssuesHashtag = "#GitHubIssues";
    private const string ProjectsHashtag = "#GitHubProjects";
    private const string SecurityHashtag = "#GitHubSecurity";
    private const string DiscussionsHashtag = "#GitHubDiscussions";
    private const string MobileHashtag = "#GitHubMobile";
    private const string PrsHashtag = "#GitHubPRs";
    private const string AiHashtag = "#AI";

    [GeneratedRegex(@"^[\p{So}\p{Sk}\p{P}\s]+", RegexOptions.Compiled)]
    private static partial Regex LeadingDecorationPattern();

    [GeneratedRegex(@"(?<=[.!?])\s+", RegexOptions.Compiled)]
    private static partial Regex SentenceSplitPattern();

    public async Task<IReadOnlyList<SocialMediaPost>> FormatThreadForXAsync(
        ChangelogEntry entry,
        bool useAi = false)
    {
        var safeMaxPostLength = GetSafePostLength();
        var plan = await BuildSummaryPlanAsync(entry, premiumMode: false, useAi, isWeekly: false);
        var header = TruncateForDisplay(entry.Title, 110);
        var threadContent = SplitSummaryContent(plan.Paragraphs, plan.TopThingsToKnow, $"{header} introduces a new GitHub changelog update.");
        var highlights = FitHighlightsForFirstPost(header, plan.TopThingsToKnow, safeMaxPostLength)
            .Select(item => $"• {SanitizeBullet(item)}")
            .ToList();
        var hashtags = FormatHashtags(GetHashtags(entry));
        var maxBodyPosts = MaxThreadPosts - 2;
        var bodyPosts = PackParagraphsIntoPosts(threadContent.RemainingParagraphs, safeMaxPostLength, maxBodyPosts);
        var posts = AssembleThread(
            header,
            threadContent.SummarySentence,
            highlights,
            bodyPosts,
            entry.Link,
            hashtags,
            safeMaxPostLength,
            MaxTweetLength);

        var preferredMedia = SelectPreferredMedia(entry);
        return posts
            .Select((text, index) => index == 0
                ? new SocialMediaPost(text, preferredMedia)
                : new SocialMediaPost(text))
            .ToList();
    }

    public async Task<SocialMediaPost> FormatPremiumPostForXAsync(
        ChangelogEntry entry,
        bool useAi = false)
    {
        var plan = await BuildSummaryPlanAsync(entry, premiumMode: true, useAi, isWeekly: false);
        var hashtags = FormatHashtags(GetHashtags(entry));
        var premiumContent = SplitSummaryContent(plan.Paragraphs, plan.TopThingsToKnow, $"{entry.Title} introduces a new GitHub changelog update.");
        var text = BuildPremiumPost(
            entry.Title,
            entry.Link,
            hashtags,
            premiumContent.SummarySentence,
            plan.TopThingsToKnow,
            premiumContent.RemainingParagraphs);

        return new SocialMediaPost(text);
    }

    public async Task<SocialMediaPost> FormatSinglePostForXAsync(
        ChangelogEntry entry,
        bool useAi = false)
    {
        var reservedLength = UrlLength
            + GetTextLength("\n\n", useXWeightedLength: true)
            + SinglePostBuffer;
        var availableForSummary = Math.Max(0, SinglePostMaxLength - reservedLength);

        string summary;
        var shouldUseAi = useAi || ShouldUseAiFromEnvironment();
        if (shouldUseAi)
        {
            if (_releaseSummarizer == null)
            {
                _logger.LogWarning("AI summaries are enabled, but ReleaseSummarizerService is not configured. Falling back to deterministic formatting for {Title}.", entry.Title);
                summary = string.Empty;
            }
            else
            {
                try
                {
                    summary = await _releaseSummarizer.SummarizeSinglePostAsync(
                        entry.Title,
                        BuildAiPayload(entry),
                        availableForSummary) ?? string.Empty;

                    if (string.IsNullOrWhiteSpace(summary))
                    {
                        _logger.LogWarning("AI single-post summary was empty for {Title}. Falling back to deterministic formatting.", entry.Title);
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogWarning(ex, "Failed to generate AI summary for {Title}. Falling back to deterministic formatting.", entry.Title);
                    summary = string.Empty;
                }
            }
        }
        else
        {
            summary = string.Empty;
        }

        if (string.IsNullOrWhiteSpace(summary))
        {
            summary = BuildSinglePostFallback(entry, availableForSummary);
        }

        summary = SinglePostSummaryNormalizer.Normalize(summary, availableForSummary);
        var text = $"{summary}\n\n{entry.Link}";
        if (!XPostLengthHelper.FitsWithinLimit(text, SinglePostMaxLength))
        {
            summary = SinglePostSummaryNormalizer.Normalize(summary, Math.Max(0, availableForSummary - 1));
            text = $"{summary}\n\n{entry.Link}";
        }

        return new SocialMediaPost(text);
    }

    private async Task<ChangelogSummaryPlan> BuildSummaryPlanAsync(
        ChangelogEntry entry,
        bool premiumMode,
        bool useAi,
        bool isWeekly)
    {
        var shouldUseAi = useAi || ShouldUseAiFromEnvironment();
        if (shouldUseAi)
        {
            if (_releaseSummarizer == null)
            {
                _logger.LogWarning("AI summaries are enabled, but ReleaseSummarizerService is not configured. Falling back to deterministic formatting for {Title}.", entry.Title);
            }
            else
            {
                try
                {
                    var plan = await _releaseSummarizer.PlanSummaryAsync(
                        entry.Title,
                        BuildAiPayload(entry),
                        entry.SummaryText,
                        entry.Labels,
                        premiumMode,
                        isWeekly);

                    if (plan != null)
                    {
                        return plan;
                    }

                    _logger.LogWarning("AI summary plan was empty for {Title}. Falling back to deterministic formatting.", entry.Title);
                }
                catch (Exception ex)
                {
                    _logger.LogWarning(ex, "Failed to generate GitHub changelog AI summary for {Title}. Falling back to deterministic formatting.", entry.Title);
                }
            }
        }

        return BuildFallbackChangelogPlan(entry.Title, entry.SummaryText, entry.ContentHtml, entry.Labels, premiumMode, isWeekly);
    }

    private static ChangelogSummaryPlan BuildFallbackChangelogPlan(
        string title,
        string summaryText,
        string contentHtml,
        IReadOnlyList<string> labels,
        bool premiumMode,
        bool isWeekly)
    {
        var features = ExtractFeatureList(contentHtml)
            .Select(StripLeadingDecoration)
            .Where(item => !string.IsNullOrWhiteSpace(item))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Take(5)
            .ToList();

        if (features.Count == 0 && !string.IsNullOrWhiteSpace(summaryText))
        {
            features = SplitIntoSentences(summaryText)
                .Select(TruncateSentence)
                .Take(4)
                .ToList();
        }

        var paragraphs = new List<string>();
        var cleanSummary = CollapseWhitespace(summaryText);
        if (!string.IsNullOrWhiteSpace(cleanSummary))
        {
            paragraphs.Add(TruncateParagraph(cleanSummary, premiumMode ? PremiumParagraphMaxLength : ThreadParagraphMaxLength));
        }

        if (features.Count > 0)
        {
            var labelText = labels.Count > 0 ? $" This update touches {string.Join(", ", labels.Take(3))}." : string.Empty;
            var highlights = string.Join(", ", features.Take(3));
            paragraphs.Add(TruncateParagraph($"Key highlights include {highlights}.{labelText}", premiumMode ? PremiumParagraphMaxLength : ThreadParagraphMaxLength));
        }

        if (paragraphs.Count == 0)
        {
            paragraphs.Add(TruncateParagraph($"{title} introduces notable GitHub product updates with practical workflow improvements.", premiumMode ? PremiumParagraphMaxLength : ThreadParagraphMaxLength));
        }

        return new ChangelogSummaryPlan
        {
            TopThingsToKnow = features.Select(SanitizeBullet).Take(4).ToList(),
            Paragraphs = paragraphs.Where(paragraph => !string.IsNullOrWhiteSpace(paragraph)).Take(2).ToList()
        };
    }

    private static IReadOnlyList<string> SelectPreferredMedia(ChangelogEntry entry)
    {
        var firstVideo = entry.Media.FirstOrDefault(item => item.MediaType == ChangelogMediaType.Video);
        if (firstVideo != null)
        {
            return [firstVideo.Url];
        }

        return entry.Media
            .Where(item => item.MediaType == ChangelogMediaType.Image)
            .Take(2)
            .Select(item => item.Url)
            .ToList();
    }

    private static string BuildSinglePostFallback(ChangelogEntry entry, int maxLength)
    {
        var plan = BuildFallbackChangelogPlan(entry.Title, entry.SummaryText, entry.ContentHtml, entry.Labels, premiumMode: false, isWeekly: false);
        var content = SplitSummaryContent(plan.Paragraphs, plan.TopThingsToKnow, "GitHub shipped a new changelog update.");
        var bulletLines = plan.TopThingsToKnow
            .Select(item => $"• {StripLeadingDecoration(CollapseWhitespace(item))}")
            .Where(item => !string.IsNullOrWhiteSpace(item))
            .Take(4)
            .ToList();

        var summary = bulletLines.Count == 0
            ? content.SummarySentence
            : $"{content.SummarySentence}\n\n{string.Join("\n", bulletLines)}";
        return SinglePostSummaryNormalizer.Normalize(summary, maxLength);
    }

    private static string BuildAiPayload(ChangelogEntry entry)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"Title: {entry.Title}");
        sb.AppendLine($"Link: {entry.Link}");
        sb.AppendLine($"Updated: {entry.Updated:O}");
        sb.AppendLine($"Changelog Type: {entry.ChangelogType}");
        sb.AppendLine($"Labels: {(entry.Labels.Count > 0 ? string.Join(", ", entry.Labels) : "none")}");

        if (entry.Media.Count > 0)
        {
            sb.AppendLine("Media:");
            foreach (var media in entry.Media)
            {
                sb.AppendLine($"- {media.MediaType}: {media.Url}");
            }
        }

        if (!string.IsNullOrWhiteSpace(entry.SummaryText))
        {
            sb.AppendLine();
            sb.AppendLine("Summary Text:");
            sb.AppendLine(entry.SummaryText);
        }

        if (!string.IsNullOrWhiteSpace(entry.ContentText))
        {
            sb.AppendLine();
            sb.AppendLine("Content Text:");
            sb.AppendLine(entry.ContentText);
        }

        if (!string.IsNullOrWhiteSpace(entry.ContentHtml))
        {
            sb.AppendLine();
            sb.AppendLine("Content HTML:");
            sb.AppendLine(entry.ContentHtml);
        }

        return sb.ToString().Trim();
    }

    private static int GetSafePostLength()
        => Math.Max(200, MaxTweetLength - ThreadBuffer);

    private static IReadOnlyList<string> AssembleThread(
        string header,
        string summarySentence,
        IReadOnlyList<string> highlights,
        IReadOnlyList<string> followUpPosts,
        string link,
        string hashtags,
        int maxPostLength,
        int singlePostMaxLength)
    {
        var singlePost = TryBuildSinglePost(
            header,
            summarySentence,
            highlights,
            followUpPosts,
            link,
            hashtags,
            singlePostMaxLength);
        if (singlePost != null)
        {
            return [singlePost];
        }

        var posts = new List<string>();
        const string leadIn = "🧵 See thread below 👇";

        var summaryBlock = string.IsNullOrWhiteSpace(summarySentence)
            ? string.Empty
            : CollapseWhitespace(summarySentence);
        var highlightBlock = highlights.Count > 0 ? string.Join("\n", highlights) : string.Empty;
        var firstPost = string.IsNullOrEmpty(summaryBlock)
            ? (string.IsNullOrEmpty(highlightBlock)
                ? $"{header}\n\n{leadIn}"
                : $"{header}\n\n{highlightBlock}\n\n{leadIn}")
            : (string.IsNullOrEmpty(highlightBlock)
                ? $"{header}\n\n{summaryBlock}\n\n{leadIn}"
                : $"{header}\n\n{summaryBlock}\n{highlightBlock}\n\n{leadIn}");

        posts.Add(EnsurePostFits(firstPost, maxPostLength));
        posts.AddRange(followUpPosts.Select(post => EnsurePostFits(post, maxPostLength)));

        var lastPostContent = $"{link}\n\n{hashtags}";
        if (posts.Count >= 2)
        {
            var prevIndex = posts.Count - 1;
            var merged = $"{posts[prevIndex]}\n\n{lastPostContent}";
            if (XPostLengthHelper.FitsWithinLimit(merged, maxPostLength))
            {
                posts[prevIndex] = merged;
            }
            else
            {
                posts.Add(EnsurePostFits(lastPostContent, maxPostLength));
            }
        }
        else
        {
            posts.Add(EnsurePostFits(lastPostContent, maxPostLength));
        }

        for (var index = 0; index < posts.Count; index++)
        {
            var indicator = $"🧵 {index + 1}/{posts.Count}";
            var withIndicator = $"{posts[index]}\n\n{indicator}";
            if (XPostLengthHelper.FitsWithinLimit(withIndicator, maxPostLength))
            {
                posts[index] = withIndicator;
                continue;
            }

            var availableForContent = maxPostLength - XPostLengthHelper.GetWeightedLength($"\n\n{indicator}");
            if (availableForContent > 0)
            {
                posts[index] = $"{XPostLengthHelper.TruncateToWeightedLength(posts[index], availableForContent)}\n\n{indicator}";
            }
        }

        return posts;
    }

    private static string? TryBuildSinglePost(
        string header,
        string summarySentence,
        IReadOnlyList<string> highlights,
        IReadOnlyList<string> followUpPosts,
        string link,
        string hashtags,
        int maxPostLength)
    {
        var sections = new List<string>();
        if (!string.IsNullOrWhiteSpace(header))
        {
            sections.Add(CollapseWhitespace(header));
        }

        var summaryBlock = string.IsNullOrWhiteSpace(summarySentence)
            ? null
            : CollapseWhitespace(summarySentence);
        if (!string.IsNullOrWhiteSpace(summaryBlock))
        {
            sections.Add(summaryBlock);
        }

        if (highlights.Count > 0)
        {
            sections.Add(string.Join("\n", highlights.Where(item => !string.IsNullOrWhiteSpace(item))));
        }

        if (followUpPosts.Count > 0)
        {
            sections.Add(string.Join("\n\n", followUpPosts.Where(post => !string.IsNullOrWhiteSpace(post))));
        }

        if (!string.IsNullOrWhiteSpace(link))
        {
            sections.Add(link);
        }

        if (!string.IsNullOrWhiteSpace(hashtags))
        {
            sections.Add(hashtags);
        }

        var candidate = string.Join("\n\n", sections.Where(section => !string.IsNullOrWhiteSpace(section)));
        return !string.IsNullOrWhiteSpace(candidate) && XPostLengthHelper.FitsWithinLimit(candidate, maxPostLength)
            ? candidate
            : null;
    }

    private static string EnsurePostFits(string text, int maxPostLength)
        => XPostLengthHelper.FitsWithinLimit(text, maxPostLength)
            ? text
            : XPostLengthHelper.TruncateToWeightedLength(text, maxPostLength);

    private static IReadOnlyList<string> FitHighlightsForFirstPost(
        string header,
        IReadOnlyList<string> highlights,
        int maxPostLength)
    {
        if (highlights.Count == 0)
        {
            return [];
        }

        const string leadIn = "🧵 See thread below 👇";
        var safeMaxLength = Math.Max(80, maxPostLength - ThreadIndicatorReserve);
        var fittedHighlights = new List<string>();

        foreach (var highlight in highlights)
        {
            var sanitizedHighlight = SanitizeBullet(highlight);
            var candidateHighlights = fittedHighlights
                .Append($"• {sanitizedHighlight}")
                .ToList();
            var highlightBlock = string.Join("\n", candidateHighlights);
            var candidate = $"{header}\n\n{highlightBlock}\n\n{leadIn}";

            if (!XPostLengthHelper.FitsWithinLimit(candidate, safeMaxLength))
            {
                break;
            }

            fittedHighlights.Add(sanitizedHighlight);
        }

        return fittedHighlights;
    }

    private static IReadOnlyList<string> PackParagraphsIntoPosts(
        IReadOnlyList<string> paragraphs,
        int maxPostLength,
        int? maxPosts = null)
    {
        var posts = new List<string>();
        var safeMaxLength = Math.Max(80, maxPostLength - ThreadIndicatorReserve);

        foreach (var paragraph in paragraphs)
        {
            var cleanParagraph = CollapseWhitespace(paragraph);
            if (string.IsNullOrWhiteSpace(cleanParagraph))
            {
                continue;
            }

            if (XPostLengthHelper.FitsWithinLimit(cleanParagraph, safeMaxLength))
            {
                posts.Add(cleanParagraph);
                continue;
            }

            var current = new StringBuilder();
            foreach (var sentence in SplitIntoSentences(cleanParagraph))
            {
                var candidate = current.Length == 0 ? sentence : $"{current} {sentence}";
                if (XPostLengthHelper.FitsWithinLimit(candidate, safeMaxLength))
                {
                    current.Clear();
                    current.Append(candidate);
                    continue;
                }

                if (current.Length > 0)
                {
                    posts.Add(current.ToString());
                    current.Clear();
                }

                posts.Add(TruncateParagraph(sentence, safeMaxLength));
            }

            if (current.Length > 0)
            {
                posts.Add(current.ToString());
            }
        }

        if (maxPosts.HasValue && posts.Count > maxPosts.Value)
        {
            var trimmedPosts = posts.Take(maxPosts.Value - 1).ToList();
            var remainingContent = string.Join(" ", posts.Skip(maxPosts.Value - 1));
            trimmedPosts.Add(TruncateParagraph(remainingContent, safeMaxLength));
            return trimmedPosts;
        }

        return posts;
    }

    private static string BuildPremiumPost(
        string header,
        string link,
        string hashtags,
        string summarySentence,
        IReadOnlyList<string> topThingsToKnow,
        IReadOnlyList<string> paragraphs)
    {
        var sb = new StringBuilder();
        sb.AppendLine(header);
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(summarySentence))
        {
            sb.AppendLine(CollapseWhitespace(summarySentence));
            sb.AppendLine();
        }

        sb.AppendLine("Top things to know:");

        foreach (var bullet in topThingsToKnow.Take(5))
        {
            sb.AppendLine($"• {SanitizeBullet(bullet)}");
        }

        if (paragraphs.Count > 0)
        {
            sb.AppendLine();
            foreach (var paragraph in paragraphs)
            {
                sb.AppendLine(CollapseWhitespace(paragraph));
                sb.AppendLine();
            }
        }

        sb.AppendLine(link);
        sb.AppendLine();
        sb.Append(hashtags);

        var text = sb.ToString().Trim();
        return XPostLengthHelper.FitsWithinLimit(text, MaxPremiumTweetLength)
            ? text
            : XPostLengthHelper.TruncateToWeightedLength(text, MaxPremiumTweetLength);
    }

    private static string FormatHashtags(IReadOnlyList<string> hashtags)
        => string.Join(" ", hashtags.Where(tag => !string.IsNullOrWhiteSpace(tag)).Distinct(StringComparer.OrdinalIgnoreCase).Take(3));

    private static IReadOnlyList<string> GetHashtags(ChangelogEntry entry)
        => GetHashtags([entry]);

    private static IReadOnlyList<string> GetHashtags(IReadOnlyList<ChangelogEntry> entries)
    {
        var corpus = string.Join(
            " | ",
            entries.Select(entry => $"{entry.Title} {string.Join(" ", entry.Labels)}"));
        var lowerCorpus = corpus.ToLowerInvariant();
        var hashtags = new List<string>();

        void AddIf(bool condition, string hashtag)
        {
            if (condition && !hashtags.Contains(hashtag, StringComparer.OrdinalIgnoreCase))
            {
                hashtags.Add(hashtag);
            }
        }

        AddIf(lowerCorpus.Contains("copilot"), CopilotHashtag);
        AddIf(lowerCorpus.Contains("actions"), ActionsHashtag);
        AddIf(lowerCorpus.Contains("codespaces"), CodespacesHashtag);
        AddIf(lowerCorpus.Contains("github cli") || lowerCorpus.Contains(" cli "), CliHashtag);
        AddIf(lowerCorpus.Contains("enterprise"), EnterpriseHashtag);
        AddIf(lowerCorpus.Contains("issues"), IssuesHashtag);
        AddIf(lowerCorpus.Contains("projects"), ProjectsHashtag);
        AddIf(lowerCorpus.Contains("security") || lowerCorpus.Contains("secret scanning") || lowerCorpus.Contains("code scanning"), SecurityHashtag);
        AddIf(lowerCorpus.Contains("discussion"), DiscussionsHashtag);
        AddIf(lowerCorpus.Contains("mobile"), MobileHashtag);
        AddIf(lowerCorpus.Contains("pull request") || lowerCorpus.Contains("pr "), PrsHashtag);
        AddIf(lowerCorpus.Contains("agent") || lowerCorpus.Contains("model") || lowerCorpus.Contains("mcp"), AiHashtag);
        hashtags.Add(GitHubHashtag);
        return hashtags.Take(3).ToList();
    }

    private static string SanitizeBullet(string text)
        => TruncateForDisplay(StripLeadingDecoration(CollapseWhitespace(text)), 72);

    private static (string SummarySentence, IReadOnlyList<string> RemainingParagraphs) SplitSummaryContent(
        IReadOnlyList<string> paragraphs,
        IReadOnlyList<string> highlights,
        string fallbackSummary)
    {
        var remainingParagraphs = new List<string>();

        foreach (var paragraph in paragraphs)
        {
            var cleanParagraph = CollapseWhitespace(paragraph);
            if (string.IsNullOrWhiteSpace(cleanParagraph))
            {
                continue;
            }

            var sentences = SplitIntoSentences(cleanParagraph);
            if (sentences.Count == 0)
            {
                continue;
            }

            var summarySentence = EnsureSentence(sentences[0]);
            if (sentences.Count > 1)
            {
                remainingParagraphs.Add(string.Join(" ", sentences.Skip(1)));
            }

            remainingParagraphs.AddRange(
                paragraphs
                    .SkipWhile(item => !ReferenceEquals(item, paragraph))
                    .Skip(1)
                    .Select(CollapseWhitespace)
                    .Where(item => !string.IsNullOrWhiteSpace(item)));

            return (summarySentence, remainingParagraphs);
        }

        var fallbackHighlight = highlights
            .Select(SanitizeBullet)
            .FirstOrDefault(item => !string.IsNullOrWhiteSpace(item));

        return (!string.IsNullOrWhiteSpace(fallbackHighlight)
                ? EnsureSentence(fallbackHighlight)
                : EnsureSentence(fallbackSummary),
            []);
    }

    private static string StripLeadingDecoration(string text)
        => LeadingDecorationPattern().Replace(text, string.Empty).Trim();

    private static List<string> SplitIntoSentences(string text)
        => SentenceSplitPattern()
            .Split(CollapseWhitespace(text))
            .Select(sentence => sentence.Trim())
            .Where(sentence => !string.IsNullOrWhiteSpace(sentence))
            .ToList();

    private static string TruncateParagraph(string text, int maxLength)
    {
        var clean = CollapseWhitespace(text);
        if (XPostLengthHelper.FitsWithinLimit(clean, maxLength))
        {
            return clean;
        }

        return XPostLengthHelper.TruncateToWeightedLength(clean, maxLength);
    }

    private static string TruncateSentence(string text)
        => TruncateForDisplay(CollapseWhitespace(text), 72);

    private static string EnsureSentence(string text)
    {
        var clean = CollapseWhitespace(text);
        if (string.IsNullOrWhiteSpace(clean))
        {
            return string.Empty;
        }

        return clean[^1] is '.' or '!' or '?'
            ? clean
            : $"{clean}.";
    }

    private static string TruncateForDisplay(string text, int maxLength)
    {
        if (string.IsNullOrWhiteSpace(text) || XPostLengthHelper.FitsWithinLimit(text, maxLength))
        {
            return text.Trim();
        }

        return XPostLengthHelper.TruncateToWeightedLength(text, maxLength);
    }

    private static string CollapseWhitespace(string text)
        => string.Join(" ", text.Split(['\r', '\n', '\t'], StringSplitOptions.RemoveEmptyEntries))
            .Trim();
}