# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core project to Azure Function App - githubchangelog

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PROJECT_PATH: './AutoGithubChangelogPoster/AutoGithubChangelogPoster.csproj'
  AZURE_FUNCTIONAPP_PUBLISH_PATH: './output'
  DOTNET_VERSION: '10.0'
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v6

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          dotnet publish '${{ env.AZURE_FUNCTIONAPP_PROJECT_PATH }}' --configuration Release --output '${{ env.AZURE_FUNCTIONAPP_PUBLISH_PATH }}'

      - name: 'Inspect publish output'
        shell: bash
        run: |
          ls -la '${{ env.AZURE_FUNCTIONAPP_PUBLISH_PATH }}'
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1.5.4
        id: fa
        with:
          app-name: 'githubchangelog'
          slot-name: 'Production'
          sku: 'flexconsumption'
          remote-build: true
          package: '${{ env.AZURE_FUNCTIONAPP_PUBLISH_PATH }}'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B6F14A3F3F5D4C25A56D430672BE7598 }}